### ISSUE TITLE
Remocon to start terminal roslaunchers

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_qt_gui#1]
You'll need a terminal 'sniffer' like in [rocon_launch](https://github.com/robotics-in-concert/rocon_multimaster/blob/hydro-devel/rocon_utilities/src/rocon_utilities/launch.py).

**Comment by stonier** [comment]
Let's drop this feature for now. Pyqt apps are real simple to make and command line freaks can always directly connect.
