### ISSUE TITLE
[app manager] UI improvements

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_qt_gui#106]
Improvements:
- [x] `App` -> `Rapp`
- [x] `Start Rapp` button left, `Stop Rapp` button right[ ]  Grey out (deactivate) `Stop Rapp` button, when no rapp is running
- [x] Grey out (deactivate) `Start Rapp` button, when rapp is running
- [x] Show rapp icons

**Comment by kentsommer** [comment]
Changes made in #141. Will close this out once that is merged.
