### ISSUE TITLE
[remocon] Handle unknown and not findable interaction excetuables

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_qt_gui#109]
This is a follow-up of the remocon-related issues in https://github.com/robotics-in-concert/rocon_tools/issues/40
- `rocon_remocon.interactive_client._determine_interaction_type` does not identify unknown interactions, i.e. not a roslauncher, not a rosrunner, not a global script. In this case, it's most likely the given interaction has been misspelled or is just not locatable.
- `rocon_remocon.interactive_client._determine_interaction_type` should throw an error, if a resource with .launch extension is provided, but cannot be found.

**Comment by stonier** [comment]
Done in https://github.com/robotics-in-concert/rocon_tools/issues/40.
