### ISSUE TITLE
Wireless statistics in the conductor graph.

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_qt_gui#11]
Do once I've exposed it over the conductor ros api:

https://github.com/robotics-in-concert/rocon_concert/issues/35

**Comment by dwlee** [comment]
I implement the first version 
d557a73fa25d762397cfc388da14179048d23564

**Comment by dwlee** [comment]
I implement the sencond version 
8c4da4bb84c87b732a4e260aceb5a1b2731a8a30

**Comment by stonier** [comment]
When I get a chance I'll have a look at this and close it if it looks great.

**Comment by stonier** [comment]
:+1:
