### ISSUE TITLE
Graph releases for indigo

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_qt_gui#113]
This isn't getting released on indigo yet because of an underlying issue with the pydot implementation. This is also why `rqt_common_plugins` is not yet released.

This issue is just for monitoring the situation.

**Comment by stonier** [comment]
Error on starting is: `NameError: global name 'dot_parser' is not defined`

**Comment by stonier** [comment]
It is probably fixed in trusty though - python-pydot was upgraded.
- [Saucy v1.0.2](http://packages.ubuntu.com/saucy/graphics/python-pydot)
- [Trusty v1.0.28](http://packages.ubuntu.com/trusty/graphics/python-pydot)

**Comment by stonier** [comment]
Can't rediscover where William was whipping up a storm about this bug though.

**Comment by stonier** [comment]
It's released, but still fails on saucy (python runtime issue).

**Comment by kentsommer** [comment]
Probably never going to be released for Saucy, but that is fine. We and everyone will be settled on the long term support release Trusty (we advise everyone to upgrade anyway).
