### ISSUE TITLE
Concert view descriptions

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_qt_gui#13]
Show descriptions in the concert view list.

Concerts often have the same name, so that is not a good identifier.

**Comment by dwlee** [comment]
Now, the descriptions information is displayed when the mouse point keeps hover at the concert list item.
How about add the edit box side of concert list and show the concert information is viewed in one?

**Comment by stonier** [comment]
Be nice to be able to view immediately. Otherwise I will have a list of 'Concert Tutorials' without an easy way to pick the right one.

**Comment by dwlee** [comment]
I made the text view widget in concert list viewer. So when user selects the concert. the concert information is displayed the it.
c657d3b7bc5d85119353a790e6d2d8cd9a4cdc3f
