### ISSUE TITLE
[rocon_remocon] launcher icon!

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_qt_gui#133]
ju se yo

**Comment by kentsommer** [comment]
For you Seonbae #136

**Comment by kentsommer** [comment]
Merge of #136 commits: 99d6d4bd66bfd1b6621040221d32adf80f095638 6dcf34057e785bf859ae8dc573108a3312b838d1 and 2885e19a6a75664524fa354da473178ca6ec7eb2 add the icon.
