### ISSUE TITLE
Conductor and Gateway Graph pydot attribute error

### ISSUE THREAD

**Issue by kentsommer** [robotics-in-concert/rocon_qt_gui#137]
The Conductor Graph shows error (Line 375): `AttributeError: 'EdgeItem' object has no attribute 'set_color'`. This error does not appear to effect the plugin's ability to run (graph is colored, this error just spams the terminal) 

![set_color edge error](https://cloud.githubusercontent.com/assets/4055025/3226417/9db002d6-f06c-11e3-90e4-04a60743c697.png)

The Gateway Graph shows error (Line 274): `AttributeError: 'NodeItem' object has no attribute 'set_color'`. As above this error does not appear to effect functionality, however, unlike above, this does not spam the terminal (prints only once). 

![set_color nodeitem error](https://cloud.githubusercontent.com/assets/4055025/3226468/5770dcfe-f06d-11e3-99eb-4ee87e067f79.png)

**Comment by kentsommer** [comment]
This is just a naming mismatch, edge_item and node_item should be using `set_node_color` instead of `set_color`. This error is fixed in: b9f5ba9c5c08b354e80b660940daf2a1af10ab6e

This can be closed out once #136 is merged.

**Comment by stonier** [comment]
:+1:
