### ISSUE TITLE
Show application icons and descriptions.

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_qt_gui#14]

**Comment by dwlee** [comment]
Icon display is not implemented,yet. but i will do it.
and the descriptions is display the edit box.

**Comment by stonier** [comment]
'edit box' 뭐예요?

**Comment by dwlee** [comment]
Edit box is kind of widget to show the text 
it is located side by the app list in app list widget

**Comment by stonier** [comment]
:+1:

**Comment by dwlee** [comment]
i fixed
786e83c73d00ec9d8ef3f30cb3e33821e7ce8c6c

**Comment by bit-pirate** [comment]
@dwlee you can close issues automatically by adding "fixes #<issue nr>" in your commit messages. There are several alternatives available. Look here for details: https://help.github.com/articles/closing-issues-via-commit-messages

You can also reference issues with your commit (link a commit to an issue) by just putting "#<issue nr>" somewhere in your commit message.

**Comment by dwlee** [comment]
thank for your advice!!

2013/11/19 Marcus Liebhardt notifications@github.com
