### ISSUE TITLE
Polish qt rapp manager

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_qt_gui#149]
It's rather unbeautiful. Wouldn't take much to spruce it up.

**Comment by mikepurvis** [comment]
Did anything ever come of this? I'm interested to deploy the app manager on some of our platforms, but I'm hoping not to have to do too much hacking on the rocon-side components myself.

**Comment by jihoonl** [comment]
@mikepurvis We haven't done any improvement yet. But I can follow up on this to assist your usecase.

I wonder how you like to use `rocon_qt_app_manager`. Do you plan to use it to just start/stop rapps inside a robot or to pair with client-side GUI application?

If you plan to pair with some other GUIs, there are [rocon_interactions](http://wiki.ros.org/rocon_interactions) and rocon_remocon to support start/stop rapp and pair with client GUI.

Or do you like to use it with different purpose?

**Comment by jihoonl** [comment]
Here is the proposed design for new qt app manager. Any thoughts?

![untitled drawing 4](https://cloud.githubusercontent.com/assets/1556736/5932405/9faf2bc6-a6f0-11e4-8872-9cd4b90fdd6b.png)

**Comment by mikepurvis** [comment]
Having half of it allocated to a permanent configuration panel seems to lock you into a pretty specific use-case, and it pretty much precludes this from being part of a larger RQT gui/perspective. Alternative suggestion:

![rqt-app-launcher](https://cloud.githubusercontent.com/assets/944666/5937811/41db60c4-a6c2-11e4-9c7b-4a51e28ac439.png)

**Comment by jihoonl** [comment]
I am not sure whether I can create tooltip dialog in QT. I will try to implement this with pop-up dialog.

**Comment by stonier** [comment]
Tooltip dialogs are very easy. We can go through that.

**Comment by stonier** [comment]
Actually...gui design is fairly straightforward but need to establish
whether we do both rapp manager and remocon frontends and rqt versions of
these.

**Comment by jihoonl** [comment]
Current status. 

Branch : https://github.com/robotics-in-concert/rocon_qt_gui/tree/new_app_manager

![icon](https://cloud.githubusercontent.com/assets/1556736/5973787/ca57a400-a8af-11e4-92dd-1d2a286a4aa4.png)

I have to figure out how to open dialog to configure rapps.

**Comment by jihoonl** [comment]
The new app manager is available in [new_app_manager](https://github.com/robotics-in-concert/rocon_qt_gui/tree/new_app_manager) branch. Please checkout. It needs some more improvements. But it should look better than before. 

![qt_app_manager](https://cloud.githubusercontent.com/assets/1556736/6017742/43503b20-abd4-11e4-8c8c-d85de6d56349.png)

**Comment by jihoonl** [comment]
**Improvements TODO**
- ~~(Done) intuitive indicator to check rapp status. (Running or available)~~
- It does not remember parameters.

**Comment by jihoonl** [comment]
Closing this. Let me know if you need further development.
