### ISSUE TITLE
[rocon_remocon] does not update cached master status

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_qt_gui#180]
when it starts up..

**Comment by stonier** [comment]
Is this happening in the background? If I recall correctly, this was intentionally done this way to make switching back and forth fast. 

If a user wanted to refresh the list, he could manually do so.

If at some point there was an incorrect master there, then it would give an error if you tried to start it.

**Comment by jihoonl** [comment]
Ok. reverted back. 

[This line](https://github.com/robotics-in-concert/rocon_qt_gui/blob/indigo/rocon_remocon/src/rocon_remocon/master_chooser.py#L205) was commented out  while I was improving speed of remocon response. Forgot to put it back.

**Comment by stonier** [comment]
:+1:
