### ISSUE TITLE
Interactive GUI

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_qt_gui#192]
Concert Conductor maintains visible concert clients in the network. The interactive GUI that allows user to control concert clients invitation status.

**Comment by jihoonl** [comment]
We may want to upgrade [concert_conductor_graph](https://github.com/robotics-in-concert/rocon_qt_gui/tree/indigo/concert_conductor_graph) to have a widget that controls concert conductor.

The controller would ...
- dynamically configure `auto_invite`, `local_clients_only` params
- Invite concert client in.
- Uninvite

**Comment by stonier** [comment]
Not going to implement.
