### ISSUE TITLE
Conductor graph application interface

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_qt_gui#24]
Needs a bit of work.
- [ ] Drop down for app list
- [x] Working remappings
- [ ] Remappings prefill with an app's interface list (ask dan when you do)
- [x] <del>Stop app should be 'inactive' if no app is running, oppositely for start app.</del>

**Comment by dwlee** [comment]
I fix the bug of "Working remappings"
1222458..be4edc3

**Comment by stonier** [comment]
No longer any app interface in the conductor graph, so cancelling this issue.
