### ISSUE TITLE
Remocon App Monitoring

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_qt_gui#3]
You need to be able to detect when the launched application stops.

This should update the remocon state, as well as the buttons.

To do this, you should use ROSLaunchParent instead of python's subprocess.

Note - [ROSLaunchParent](https://github.com/ros/ros_comm/blob/hydro-devel/tools/roslaunch/src/roslaunch/parent.py) has an argument for process_listeners to let you know when the process finishes.

---

[Donguk] Already uses ROSLaunchParent, but from a separate script in a subprocess. Apprently there is a problem with qt running roslaunch.start(). We'd have to solve this first.

**Comment by dwlee** [comment]
i remember that why did use the subprocess.
when i stop launched app, i use the launch.shutdown()
but this case, the qt remocon is shutdown togather with lanched app

**Comment by stonier** [comment]
Thats odd. Can only happen if it has the same PID as the remocon itself.

**Comment by dwlee** [comment]
I fixed this issue.
Now user is able to launch already launched again.
https://github.com/robotics-in-concert/rocon_qt_gui/commit/bfc4af99ad03efeb019498d72f937c133e715902
