### ISSUE TITLE
Make a license branch like the other rocon repos

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_qt_gui#34]
There is no license with any of the rocon_qt_gui packages.

Just copy the way we do it for the other rocon stacks, e.g. create a branch like:

https://github.com/robotics-in-concert/rocon_app_platform/tree/license

and at the top of every python file, add the following comments:

```
#
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_qt_gui/license/LICENSE
#
```

**Comment by dwlee** [comment]
I fix
https://github.com/robotics-in-concert/rocon_qt_gui/commit/6ebe3b9741977e79500a527b13b34afd8cfc6e46
