### ISSUE TITLE
Remocon support for web url's

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_qt_gui#41]
Currently it can start roslaunchers, rosrunnables, executables, but not web url's. Example from [admin service](https://github.com/robotics-in-concert/rocon_concert/blob/hydro-devel/concert_services/admin/admin.interactions).

First step, get support in to handle something like:

```
name: http://wiki.ros.org/rocon
```

It should open up this web page.

**Comment by dwlee** [comment]
Q) Open up in a qt webkit widget of some sort? Open up in system default browser?

**Comment by dwlee** [comment]
@jihoonl how important is the type of web browser for web apps?

Investigate how much 'web app' support is in the qt webkit widgets. If it is not enough, we need to detect the browsers on the system and install/give warning if we can't find a good one.

**Comment by dwlee** [comment]
Using wt webkit rqt 

> - You check about your browser whether to support html5 and css or not  using this [site](http://html5test.com/) 
> - Qt  web kit is Low support than chrome.

Using new browsers

> - Generally using browsers(chrome, IE, firefox, ... ) support all most whole function of html 5 and css
> - Default browser recommendation to chrome.
> - 3개 os 지원 (linux, windows, mac)
> - But, in case of using new browser, difficult to communication with qt remocon. The browser has to communication with concert, independently.

**Comment by stonier** [comment]
Using new browser should be no problem for qt remocon. Documentation needs no ros communication. Web apps handle the ros communication on their own (you would need to pass them the parameters, remappings and probably ros master uri).

Just detect it, python Popen it (like I do for global executables - it can already start them). The only additional work is to pass it a url (command line argument?)

**Comment by stonier** [comment]
Web tools all run fine on chrome, ie and firefox? We'd need to identify detect minimum version specifications for qt remocon to guarantee jihoon's web apps can run before launching.

**Comment by dwlee** [comment]
You can see and check the html5 support browser; [link](http://mightydigital.com/top-5-html5-compatibility-charts-web-mobile-developers/)
As above link, IE, firefox and so on support the html5(but, IE is over Ver. 10). 
And I think the  jihoon's web apps is made based on html5 and css. So it works well on the browser used generally.

**Comment by jihoonl** [comment]
Robot Web Tool modules are built with browser compatibility consideration.  So Webtools are runnable as long as websocket is enabled. 

I suggest to use Chrome as default browser since it supports the best among others instead of supporting all. It supports all 3 major OS and best HTML5 compatibility score.

**Comment by stonier** [comment]
@dwlee I think @jihoonl's comment is a good suggestion. Rocon is not a product yet, so limiting to one browser is fine while we're developing so long as there is no great difficulty scaling up later. 

Trying to support everything we can do later if we start using it as a product.

**Comment by stonier** [comment]
Looks like this page is a good reference for [websockets](http://caniuse.com/websockets) version support.

**Comment by dwlee** [comment]
Ok. 
So, I will implement the webapp launcher in remocon using Chrome browser.

**Comment by dwlee** [comment]
I update about this issue. 
a61c40dd0754ca512339e64e75407996d0986514

but the some problem remains.
1. only support chrome.
   Now. web app is launched using chrome. Basically remocon support 5 browsers (minimum 4(opera, firefox, chrome)).
2. Creation session in existing browser
   As soon as launching the web browser, call the kill process listener because the chrome instance is already creation. But the new web browser is not terminated. So, we can not terminate the web app through remocon.
3. How to send the parameter and remapping
   Not yet.
   The web app send the parameter and remapping to other client using url.

**Comment by stonier** [comment]
I had a look at a61c40dd0754ca512339e64e75407996d0986514. 

I would suggest parsing [freedesktop](http://www.freedesktop.org/wiki/) files (i.e. `~/.local/share/...` is not practical. It introduces an unnecessary dependency on a freedesktop windowing environment. That is, it will break if you use something that isn't freedesktop client (e.g. enlightenment v1, these days only a little likely). It will also break if chrome desktop data gets installed into the system directories, not the user directories (very likely).

Much better to depend on chrome itself. Use [rocon_utilities.which](https://github.com/robotics-in-concert/rocon_multimaster/blob/hydro-devel/rocon_utilities/src/rocon_utilities/system.py#L24) or even better, python subprocess `google-chrome --version`. 

Then you have no dependency on freedesktop.

**Comment by stonier** [comment]
`2.` I can't see any way of terminating it either. You could possibly do something with a unique --user-data-dir (e.g. `~/.chrome_13af289d9e`) as that starts a new instance of chrome...But that's getting tricky.

At the very least, the remocon should disable the stop app button for these particular launchers.

**Comment by stonier** [comment]
`3.` Jihoon can let you know what the format for parameters and remappings should be. I believe they should be the same as previously used for the headless launcher.

**Comment by dwlee** [comment]
For the reference

https://github.com/rosjava/android_remocons/blob/master/common_tools/src/main/java/com/github/rosjava/android_remocons/common_tools/AppLauncher.java#L150

https://github.com/robotics-in-concert/rocon_demos/blob/cafe_concert/opp_demo/services/cafe_delivery/cafe_delivery.interactions#L19-L32

**Comment by dwlee** [comment]
I implement.
a12264a43db1f60e3226adcbec5d8896633b2866
1. change the sniffing browser more simply.
2. The chrome browser process is terminated as soon ad launch the chrome app through remocon. So the "Stop All Apps" button is disable automatically.
3.  I make the url synthesizer referenced android remocon. 
   But some strange one in the "dorothy order web app". the android remocon send the "MasterURI" argument besides remapping and parameter to web app. I don't understand this. the parameter already contains the masteruri information. why does the same information send  to webapp? 
   Anyone  know?

**Comment by stonier** [comment]
I'd forgotten about the MasterURI. The remocon does need to add that to the url so the web app can connect to the ros master. This remocon will need to also add the MasterURI in the same way for ros web apps.

But here is the problem - this is only for ros web apps. If the url is a roswiki documentation url - then passing a MasterURI will break it.

Does the remocon start qt apps with ROS_IP/ROS_HOSTNAME and master uri configured?

**Comment by stonier** [comment]
The master uri problem: #44

Shall we close this issue and continue in #44?
