### ISSUE TITLE
Remocon Master URI for web apps

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_qt_gui#44]
The remocon needs to pass this variable to web app url's, but NOT regular url's (like pointers to documentation). 

Possible solutions:
- A special symbol in a rocon interactions url that the remocon detects and substitutes for the master uri.
- An extra field in the rocon interactions specification, e.g. `requires_master_uri`.

**Comment by jihoonl** [comment]
Does it need extra field for master uri? Can master_uri be specified in parameters?
The dorothy web app was actually parsing rosbridge address and port configured in parameter. Does web app need to know the master uri?

**Comment by stonier** [comment]
It of course goes in as a parameter, but let's rewind a bit...

> But some strange one in the "dorothy order web app". the android remocon send the "MasterURI" argument besides remapping and parameter to web app. 

What is this MasterURI for? You're talking about a rosbridge uri, not a rosmaster uri.

Probably the most important point - this uri can't be hardcoded into a service .interactions file. The service developer has no idea what uri's will be used on site. So a flag or substitutable symbol of some sort or discovery method is needed.

_Question_: put in the remocon or the interactions manager? 

The interactions manager is probably better - this is a common need for all remocons.

_Question_: how should the interactions manager discover the rosbridge info? Does rosbridge publish this info at all (e.g. on the param server?).

**Comment by jihoonl** [comment]
> What is this MasterURI for? You're talking about a rosbridge uri, not a rosmaster uri.
> Probably the most important point - this uri can't be hardcoded into a service .interactions file. The service developer has no idea what uri's will be used on site. So a flag or substitutable symbol of some sort or discovery method is needed.

Yeah hardcoding uri is not a correct solution. But using master uri may in dangerous too. Because it assumes that rosbridge and concert master are running under same ip address. I think interaction_manager should read rosbridge address and port parameter from rosparam.

> Question: how should the interactions manager discover the rosbridge info? Does rosbridge publish this info at all (e.g. on the param server?).

Yes, it is readable from rosparam.
https://github.com/RobotWebTools/rosbridge_suite/blob/hydro-devel/rosbridge_server/launch/rosbridge_websocket.launch#L21-L22

**Comment by stonier** [comment]
Unfortunately these are private parameters...

**Comment by stonier** [comment]
launcher args...we can pass them in here and also to the rocon_interactions separately.

**Comment by stonier** [comment]
Q) What form does the address take? Does it include the schema? i.e. `192.168.1.1` or `http://192.168.1.1`?

Q) If it's not set, does it default to the ros master uri or localhost?

**Comment by jihoonl** [comment]
> Q) What form does the address take? Does it include the schema? i.e. `192.168.1.1` or `http://192.168.1.1`?

It is IP address or hostname. Use without http://

> Q) If it's not set, does it default to the ros master uri or localhost?

It sets to localhost by default. Since it is a webserver, it needs to communicate with ROS master but it is not necessary to stay in local.

**Comment by stonier** [comment]
:+1: got it.

**Comment by stonier** [comment]
This was removed from `rocon_remocon` (05856d6525ee4288aa48995bc935676524e6771c) and implemented back in `rocon_interactions`: https://github.com/robotics-in-concert/rocon_tools/commit/531a35c8f5e38727597797598ec3741e7909825d
