### ISSUE TITLE
Development of Qt teleop App

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_qt_gui#45]
We have to discussion of Qt teleop app development.
@stonier  What can i do this development?

**Comment by stonier** [comment]
Yes. After lunch.

**Comment by stonier** [comment]
1st Step:

**Dan**
- [x] Teleop service recruit two teleop turtles static link graph style (hack till req-sched is fully in).
- [x] Teleop service provide a latched publisher listing available/pre-emptible resources
  - Make a msg for this
  - Provide Mr Do the name for this
  - Publish rocon_uri's for two turtles on there.

**Mr Do**
- Subscribe to the latched publisher
- Design the interface with three parts:
  - Panel on the left listing up the name part of the rocon uri's read from the latched publisher
  - Main window (on the right) showing the result of a png/jpeg compressed image topic from the robot
  - Bottom window (on the right) giving keyboard teleop instructions.

**Comment by dwlee** [comment]
I make the teleop app of first integration version.75f430d..066aacc

But, I have some question.
- Q) @stonier  I send the capture service with service pair
  but i do not receive the callback. only error callback about the time out error.
  i used below code .

```
request = rocon_service_msgs.CaptureTeleopRequest()

request.rocon_uri = rocon_uri

msg_id = self.capture_teleop(request, timeout=rospy.Duration(10.0), callback=self.callback, error_callback=self.error_callback)
```

**Comment by dwlee** [comment]
I captured the "guimul" in turtle concert. 
the result callback is success. but the generated topic is 

```
/kobuki/cmd_vel
/kobuki/compressed_image
```

Please check.. @stonier

**Comment by stonier** [comment]
Bug fixed in https://github.com/robotics-in-concert/rocon_services/commit/30db938f7e2b99b1bd99230f280445bd50bf20d1. Wasn't passing on the rocon uri properly.

**Comment by stonier** [comment]
I think we hit our targets here. Will open up new issues for remaining work.
