### ISSUE TITLE
When to use what icons

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_qt_gui#5]
You do not need to save concert icons.

If there is no connection, you just need the unknown icon.

If there is a connection, `/concert/info` will save you.

**Comment by dwlee** [comment]
i have to save the icon image. 
Because the check up process is sub-process. 
so i send the icon data to main path as a icon path

**Comment by stonier** [comment]
Done?

**Comment by dwlee** [comment]
yes. i save the cache and icon file to temporary folder("~/.ros/rocon/")
