### ISSUE TITLE
Caching in rocon remocon a bit odd

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_qt_gui#51]
**Remocon Subprocess**
- `_read_cache` : triggered in `init`
- `_write_cache` : triggered in `refresh role list` (which is called on button press or `init role list`.

**Remocon Main**
- `_read_cache` : triggered in refresh rocon master list.

**Comment by stonier** [comment]
Actions:
- Just one read_cache function?
- Answer what is this caching plan doing exactly?

**Comment by dwlee** [comment]
Q1) Just one read_cache function?
I check this problem.
I don't delete `_read_cache` and `_write_cache` in `RemoconSub` class when end the test. 
These functions only use in the registeration and check validation of concert.

Q2) Answer what is this caching plan doing exactly?

The cached information of concert is used the update the concert list when first start remocon.
And when the adding , delete, refresh the concert, this cache file update.

**Comment by dwlee** [comment]
I remove cache read and write api in remoconsub class
f31eaa1e78ab3a2636dc8e0ca19716a6a3a01729

**Comment by stonier** [comment]
I'll reopen if I find a problem again.
