### ISSUE TITLE
Remocon will have a problem with installation

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_qt_gui#54]
It's going to be missing it's support scripts - `rocon_remocon_sub` and `rocon_remocon_check_up` will not get installed.

These are also referenced relatively in the source code (remocon's `script_path` variable).

**Comment by stonier** [comment]
@dwlee can you take a look at this?

Do a `yujin_make --install`, then source the setup.bash in the install directory.

You can then test with 

```
> rocon_launch chatter_concert chatter.concert --screen
> rocon_remocon
```

Ask me if you're not certain.

**Comment by dwlee** [comment]
Ok, I see. 
I test it.

**Comment by dwlee** [comment]
I fix.
78b19fa..bd327d4

**Comment by stonier** [comment]
Remaining issues:
- The sub-scripts should go in the _package bin_, not the _global bin_. You don't want the user accessing `rocon_remocon_sub` and `rocon_remocon_check_up` with tab completion on the command line.

To put in the package bin, instead of `setup.py`, add the line to your `CMakeLists.txt`:

```
install(
    PROGRAMS 
        scripts/rocon_remocon_check_up
        scripts/rocon_remocon_sub
    DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
    )
```
- Testing in the install space is important - the following line will break the remocon because the scripts are installed in different locations to the source tree.

```
self.scripts_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../scripts/")
```

This will be a bit more difficult to solve - I might have to help you with that.

**Comment by dwlee** [comment]
I aready fixed about this issue.
And you can see here.
bd327d4ad2e6457cba8d2bbced2d5fd884f8216b

**Comment by stonier** [comment]
There will still be a problem with the `remocon_check_up` call. See above...i.e. this will fail:

```
self.scripts_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../scripts/")
```

Testing from the install space is important. Leaving this open till we fix that.

**Comment by stonier** [comment]
@dwlee In the diff above, [this function](https://github.com/robotics-in-concert/rocon_qt_gui/commit/3057712e21b255008abe808552af5a68febbf04a#diff-0d6458f3680da63e7ba42f090e2e6674R59) helps find the scripts in devel or install spaces.

I use that to define some class variables [here](https://github.com/robotics-in-concert/rocon_qt_gui/commit/3057712e21b255008abe808552af5a68febbf04a#diff-a2481c0b789ca75b4b8b479a51449cfcR45) and [here](https://github.com/robotics-in-concert/rocon_qt_gui/commit/3057712e21b255008abe808552af5a68febbf04a#diff-49406cb17f1e00875dac1110ed56b09bR246)
