### ISSUE TITLE
Teleop resource capture/release updates

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_qt_gui#67]
If we can't do releasing, often have to stop the whole solution and restart it after testing once.
- [x] add a boolean variable to the request (true - capture, false - release) [@stonier]
- [x] add release functionality to the teleop pimp [@stonier]
- [x] capture a robot on double click
- [x] highlight the captured robot in the list
  - double clicking a captured robot releases it
  - double click a different robot releases the current and captures another
  - a release button?
- [x] release currently captured robot on closing app

**Comment by stonier** [comment]
Do we need buttons?

**Comment by dwlee** [comment]
The button is intuitive. but I think the double click is the more convenient for user. 
How about add the double click function instead of removing the capture button?

**Comment by stonier** [comment]
> How about add the double click function instead of removing the capture button?

You mean having both - double click and button?

**Comment by dwlee** [comment]
Yes, it is!

**Comment by stonier** [comment]
Ok.

**Comment by stonier** [comment]
Ok, my bad. CaptureTeleop didn't have the bool variable for releasing!

**Comment by dwlee** [comment]
I fixed
efa68cf..03b1e59
- possible to capture using double click
- add the highlight and capture tag about captured robot
- add the release button

**Comment by dwlee** [comment]
Can I ask the question @stonier?
The teleop app is try to unregister the publisher about the captured teleop `cmd_vel` when release teleop. 

but bottom warning always occurred.

```
[WARN] [WallTime: 1395297289.149673] Could not process inbound connection: [/rqt_gui_py_node_4935] is not a publisher of [/kobuki/cmd_vel]. Topics are [['/rosout', 'rosgraph_msgs/Log'], ['/services/teleop/capture_teleop/request', 'rocon_service_msgs/CaptureTeleopPairRequest']]{'message_definition': '# This expresses velocity in free space broken into its linear and angular parts.\nVector3  linear\nVector3  angular\n\n================================================================================\nMSG: geometry_msgs/Vector3\n# This represents a vector in free space. \n\nfloat64 x\nfloat64 y\nfloat64 z\n', 'callerid': '/kobuki/turtle_teleop', 'tcp_nodelay': '0', 'md5sum': '9f195f881246fdfa2798d1d3eebca84a', 'topic': '/kobuki/cmd_vel', 'type': 'geometry_msgs/Twist'}

```

 I use this code.
https://github.com/robotics-in-concert/rocon_qt_gui/blob/teleop_app_patch/concert_teleop_app/src/concert_teleop_app/teleop_app_info.py#L187-L192

Do you do something?

**Comment by stonier** [comment]
This is because the kobuki's subscriber is killed when the app stops...and then it requests to the concert to unflip it. Your qt program is unregistering while there is still this ghost on the concert level.

To fix it we need the unflip before the stop app. Wait for response and then stop app. I should make an issue for this on rocon_multimaster, but just ignore it for now - it doesn't hurt anybody except your eyes.

**Comment by stonier** [comment]
This is working now.
