### ISSUE TITLE
How to send the host name argument

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_qt_gui#7]
When check the validation of concert and concert to concert, remocon needs the ros host name. 
so, user have to typing the host name with running the remocon as argument.
1. using ROS_HOSTNAME export.
2. automatically setting.
3. keeping existing method.

**Comment by stonier** [comment]
1. is not an option, it will break if you start remocon from a different pc.
2. you can check qt_ros code, it does this.
3. you need to autodect interfaces and maybe show a drop down menu for the user to select.
4. is a nice idea.

**Comment by dwlee** [comment]
yes i will check wt option

**Comment by stonier** [comment]
I have a box for setting this in qt_ros: You can see here:

http://wiki.ros.org/qt_create/Tutorials/Qt%20App%20Templates
- If check environment is flagged, then I use environment ROS_IP or ROS_HOSTNAME
- If not checked, I use a user specified, cached value.

**Comment by dwlee** [comment]
I fixed.
98249cb..2c7eaad
