### ISSUE TITLE
A good virtual joystick!

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_qt_gui#71]
Ours sucks for doing speed/rotational speed control. Really need the circle style virtual joystick.
- Should modify velocity with the radial direction (work like old android app).
- @jihoonl suggested key bindings for the joy stick as an option.

Low priority for the qt app.

**Comment by dwlee** [comment]
I fixed.
And I added the keyboard controller.
9bd2604..4918687

**Comment by stonier** [comment]
Need some more refined working of the velocities otherwise it will really really **suck** on real robots.

Currently there is only 1) 0 and 2) full speed! Should be relatively easy to convert a radius and angle into appropriate cmd_vel and twist.

Is this hard to implement donguk?

I love the big scary eye!

**Comment by dwlee** [comment]
@stonier It is simple implementation .
I will make it and re-open the issue added  by jihoonl.
How about close this issue? I have a nice feeling when issue is closed. :)

**Comment by stonier** [comment]
I like to keep this one open as it is a _full story_ about the joystick implementation. Pull requests come in and around the story.

Your pull requests are getting closed so you can get a good feeling from them :stuck_out_tongue_winking_eye:

Jihon's is about keyboard teleop, not joystick right?

**Comment by stonier** [comment]
Closing...all looking good now. @dwlee reopen if you think it still needs more work.
