### ISSUE TITLE
Add the button of velocity setting

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_qt_gui#77]
as tiltle explains.

**Comment by stonier** [comment]
I'd much rather a proper virtual joystick than putting time into this.

**Comment by stonier** [comment]
Follow up in #71

**Comment by stonier** [comment]
It's now got maximum velocity parameters which can be configured from the interaction settings so you can get a desired startup behaviour, see #121.

It would still be good to have a dial or something so you can modify this runtime though. We don't absolutely need this though, so dropping it for now. If someone really wants it, reopen this and scratch your itch ;)
