### ISSUE TITLE
Better master detection

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_qt_gui#80]
- [x] parallelise and background startup master checks
- [x] only check for newly added master when adding. Not all!

**Comment by dwlee** [comment]
OK. I will change these.

**Comment by dwlee** [comment]
@stonier Why do you comment the message box which is popup when user select wrong concert ?
(you can see the comment code [here](https://github.com/robotics-in-concert/rocon_qt_gui/blob/hydro-devel/rocon_remocon/src/rocon_remocon/remocon.py#L610))
I think that I need it to inform user the error or warning.

**Comment by stonier** [comment]
> @stonier Why do you comment the message box which is popup when user select wrong concert ?
> (you can see the comment code [here](https://github.com/robotics-in-concert/rocon_qt_gui/blob/hydro-devel/rocon_remocon/src/rocon_remocon/remocon.py#L610))
> I think that I need it to inform user the error or warning. 

I couldn't work out when it showed before - if you need it, use it and then teach me how it works :stuck_out_tongue_winking_eye:

**Comment by stonier** [comment]
Could use a funky way of telling the user it is scanning, e.g. modify icons currenty scanning, but this will do for now.
