### ISSUE TITLE
Make use of new QtAppManager class in concert_conductor_graph

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_qt_gui#89]
Both UI's should use the same app manager code, i.e. class.

**Comment by stonier** [comment]
Should talk about if this component actually fits in the concert conductor graph. I don't think it does - someone playing around with start/stop apps will create an interference in the workflow that services-scheduler-client app managers have without any of those things being aware of it. Bound to break.

**Comment by stonier** [comment]
Removed from the conductor as it would need special handling and doesn't have a use case in the concert for now. Reopen if you want to explore this issue again.
